version: '3'

services:
  php-container:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    #  - "9003:9003"
    volumes:
      - ./src:/var/www/html
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
      #XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    extra_hosts:
      - host.docker.internal:host-gateway
      
    restart: always