version: '3'

services:
  php-container:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
      
    restart: always
