version: '3'

services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  php-container:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - 443:443 # for future ssl traffic
    volumes:
      - ./src:/var/www/html
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
      #XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306